# Write your MySQL query statement below
SELECT NAME, COALESCE(SUM(DISTANCE),0) AS TRAVELLED_DISTANCE
FROM USERS U LEFT JOIN RIDES R
ON U.ID = R.USER_ID
GROUP BY U.ID
ORDER BY TRAVELLED_DISTANCE DESC, NAME ASC;